/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppUsersRolesRouteImport } from './routes/_app/users/roles'
import { Route as AppUsersMembershipRouteImport } from './routes/_app/users/membership'
import { Route as AppUsersAllRouteImport } from './routes/_app/users/all'
import { Route as AppSettingsSocialRouteImport } from './routes/_app/settings/social'
import { Route as AppSettingsSeoRouteImport } from './routes/_app/settings/seo'
import { Route as AppSettingsPaymentsRouteImport } from './routes/_app/settings/payments'
import { Route as AppSettingsLegalRouteImport } from './routes/_app/settings/legal'
import { Route as AppSettingsContactRouteImport } from './routes/_app/settings/contact'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app/settings/company'
import { Route as AppProjectsDashboardRouteImport } from './routes/_app/projects/dashboard'
import { Route as AppProjectsAllRouteImport } from './routes/_app/projects/all'
import { Route as AppProductsVariantsRouteImport } from './routes/_app/products/variants'
import { Route as AppProductsSubcategoriesRouteImport } from './routes/_app/products/subcategories'
import { Route as AppProductsNewArrivalRouteImport } from './routes/_app/products/new-arrival'
import { Route as AppProductsDashboardRouteImport } from './routes/_app/products/dashboard'
import { Route as AppProductsCategoriesRouteImport } from './routes/_app/products/categories'
import { Route as AppProductsBrandsRouteImport } from './routes/_app/products/brands'
import { Route as AppProductsBestSellingRouteImport } from './routes/_app/products/best-selling'
import { Route as AppProductsAtlKitsRouteImport } from './routes/_app/products/atl-kits'
import { Route as AppProductsAllRouteImport } from './routes/_app/products/all'
import { Route as AppOrdersTrackerRouteImport } from './routes/_app/orders/tracker'
import { Route as AppOrdersShippingMethodsRouteImport } from './routes/_app/orders/shipping-methods'
import { Route as AppOrdersReturnsRouteImport } from './routes/_app/orders/returns'
import { Route as AppOrdersInvoicesRouteImport } from './routes/_app/orders/invoices'
import { Route as AppOrdersAllRouteImport } from './routes/_app/orders/all'
import { Route as AppMarketingTrendingRouteImport } from './routes/_app/marketing/trending'
import { Route as AppMarketingHotDealsRouteImport } from './routes/_app/marketing/hot-deals'
import { Route as AppMarketingFlashSalesRouteImport } from './routes/_app/marketing/flash-sales'
import { Route as AppMarketingComboOffersRouteImport } from './routes/_app/marketing/combo-offers'
import { Route as AppMarketingBannersRouteImport } from './routes/_app/marketing/banners'
import { Route as AppContentVideoGalleryRouteImport } from './routes/_app/content/video-gallery'
import { Route as AppContentTutorialsRouteImport } from './routes/_app/content/tutorials'
import { Route as AppContentFaqRouteImport } from './routes/_app/content/faq'
import { Route as AppContentBlogRouteImport } from './routes/_app/content/blog'
import { Route as AppB2bVideoGalleryRouteImport } from './routes/_app/b2b/video-gallery'
import { Route as AppB2bJobApplicationsRouteImport } from './routes/_app/b2b/job-applications'
import { Route as AppB2bInquiriesRouteImport } from './routes/_app/b2b/inquiries'
import { Route as AppB2bCareersRouteImport } from './routes/_app/b2b/careers'
import { Route as AppAffiliateReferralTrackingRouteImport } from './routes/_app/affiliate/referral-tracking'
import { Route as AppAffiliatePayoutsRouteImport } from './routes/_app/affiliate/payouts'
import { Route as AppAffiliateKycRouteImport } from './routes/_app/affiliate/kyc'
import { Route as AppAffiliateDashboardRouteImport } from './routes/_app/affiliate/dashboard'
import { Route as AppAffiliateCommissionTiersRouteImport } from './routes/_app/affiliate/commission-tiers'
import { Route as AppAffiliateAllRouteImport } from './routes/_app/affiliate/all'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRolesRoute = AppUsersRolesRouteImport.update({
  id: '/users/roles',
  path: '/users/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersMembershipRoute = AppUsersMembershipRouteImport.update({
  id: '/users/membership',
  path: '/users/membership',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersAllRoute = AppUsersAllRouteImport.update({
  id: '/users/all',
  path: '/users/all',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSocialRoute = AppSettingsSocialRouteImport.update({
  id: '/settings/social',
  path: '/settings/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSeoRoute = AppSettingsSeoRouteImport.update({
  id: '/settings/seo',
  path: '/settings/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPaymentsRoute = AppSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLegalRoute = AppSettingsLegalRouteImport.update({
  id: '/settings/legal',
  path: '/settings/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsContactRoute = AppSettingsContactRouteImport.update({
  id: '/settings/contact',
  path: '/settings/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsDashboardRoute = AppProjectsDashboardRouteImport.update({
  id: '/projects/dashboard',
  path: '/projects/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsAllRoute = AppProjectsAllRouteImport.update({
  id: '/projects/all',
  path: '/projects/all',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsVariantsRoute = AppProductsVariantsRouteImport.update({
  id: '/products/variants',
  path: '/products/variants',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsSubcategoriesRoute =
  AppProductsSubcategoriesRouteImport.update({
    id: '/products/subcategories',
    path: '/products/subcategories',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductsNewArrivalRoute = AppProductsNewArrivalRouteImport.update({
  id: '/products/new-arrival',
  path: '/products/new-arrival',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsDashboardRoute = AppProductsDashboardRouteImport.update({
  id: '/products/dashboard',
  path: '/products/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsCategoriesRoute = AppProductsCategoriesRouteImport.update({
  id: '/products/categories',
  path: '/products/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsBrandsRoute = AppProductsBrandsRouteImport.update({
  id: '/products/brands',
  path: '/products/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsBestSellingRoute = AppProductsBestSellingRouteImport.update({
  id: '/products/best-selling',
  path: '/products/best-selling',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsAtlKitsRoute = AppProductsAtlKitsRouteImport.update({
  id: '/products/atl-kits',
  path: '/products/atl-kits',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsAllRoute = AppProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersTrackerRoute = AppOrdersTrackerRouteImport.update({
  id: '/orders/tracker',
  path: '/orders/tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersShippingMethodsRoute =
  AppOrdersShippingMethodsRouteImport.update({
    id: '/orders/shipping-methods',
    path: '/orders/shipping-methods',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrdersReturnsRoute = AppOrdersReturnsRouteImport.update({
  id: '/orders/returns',
  path: '/orders/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersInvoicesRoute = AppOrdersInvoicesRouteImport.update({
  id: '/orders/invoices',
  path: '/orders/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersAllRoute = AppOrdersAllRouteImport.update({
  id: '/orders/all',
  path: '/orders/all',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingTrendingRoute = AppMarketingTrendingRouteImport.update({
  id: '/marketing/trending',
  path: '/marketing/trending',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingHotDealsRoute = AppMarketingHotDealsRouteImport.update({
  id: '/marketing/hot-deals',
  path: '/marketing/hot-deals',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingFlashSalesRoute = AppMarketingFlashSalesRouteImport.update({
  id: '/marketing/flash-sales',
  path: '/marketing/flash-sales',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingComboOffersRoute = AppMarketingComboOffersRouteImport.update({
  id: '/marketing/combo-offers',
  path: '/marketing/combo-offers',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingBannersRoute = AppMarketingBannersRouteImport.update({
  id: '/marketing/banners',
  path: '/marketing/banners',
  getParentRoute: () => AppRoute,
} as any)
const AppContentVideoGalleryRoute = AppContentVideoGalleryRouteImport.update({
  id: '/content/video-gallery',
  path: '/content/video-gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppContentTutorialsRoute = AppContentTutorialsRouteImport.update({
  id: '/content/tutorials',
  path: '/content/tutorials',
  getParentRoute: () => AppRoute,
} as any)
const AppContentFaqRoute = AppContentFaqRouteImport.update({
  id: '/content/faq',
  path: '/content/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppContentBlogRoute = AppContentBlogRouteImport.update({
  id: '/content/blog',
  path: '/content/blog',
  getParentRoute: () => AppRoute,
} as any)
const AppB2bVideoGalleryRoute = AppB2bVideoGalleryRouteImport.update({
  id: '/b2b/video-gallery',
  path: '/b2b/video-gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppB2bJobApplicationsRoute = AppB2bJobApplicationsRouteImport.update({
  id: '/b2b/job-applications',
  path: '/b2b/job-applications',
  getParentRoute: () => AppRoute,
} as any)
const AppB2bInquiriesRoute = AppB2bInquiriesRouteImport.update({
  id: '/b2b/inquiries',
  path: '/b2b/inquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppB2bCareersRoute = AppB2bCareersRouteImport.update({
  id: '/b2b/careers',
  path: '/b2b/careers',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateReferralTrackingRoute =
  AppAffiliateReferralTrackingRouteImport.update({
    id: '/affiliate/referral-tracking',
    path: '/affiliate/referral-tracking',
    getParentRoute: () => AppRoute,
  } as any)
const AppAffiliatePayoutsRoute = AppAffiliatePayoutsRouteImport.update({
  id: '/affiliate/payouts',
  path: '/affiliate/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateKycRoute = AppAffiliateKycRouteImport.update({
  id: '/affiliate/kyc',
  path: '/affiliate/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateDashboardRoute = AppAffiliateDashboardRouteImport.update({
  id: '/affiliate/dashboard',
  path: '/affiliate/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateCommissionTiersRoute =
  AppAffiliateCommissionTiersRouteImport.update({
    id: '/affiliate/commission-tiers',
    path: '/affiliate/commission-tiers',
    getParentRoute: () => AppRoute,
  } as any)
const AppAffiliateAllRoute = AppAffiliateAllRouteImport.update({
  id: '/affiliate/all',
  path: '/affiliate/all',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/support': typeof AppSupportRoute
  '/affiliate/all': typeof AppAffiliateAllRoute
  '/affiliate/commission-tiers': typeof AppAffiliateCommissionTiersRoute
  '/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/affiliate/kyc': typeof AppAffiliateKycRoute
  '/affiliate/payouts': typeof AppAffiliatePayoutsRoute
  '/affiliate/referral-tracking': typeof AppAffiliateReferralTrackingRoute
  '/b2b/careers': typeof AppB2bCareersRoute
  '/b2b/inquiries': typeof AppB2bInquiriesRoute
  '/b2b/job-applications': typeof AppB2bJobApplicationsRoute
  '/b2b/video-gallery': typeof AppB2bVideoGalleryRoute
  '/content/blog': typeof AppContentBlogRoute
  '/content/faq': typeof AppContentFaqRoute
  '/content/tutorials': typeof AppContentTutorialsRoute
  '/content/video-gallery': typeof AppContentVideoGalleryRoute
  '/marketing/banners': typeof AppMarketingBannersRoute
  '/marketing/combo-offers': typeof AppMarketingComboOffersRoute
  '/marketing/flash-sales': typeof AppMarketingFlashSalesRoute
  '/marketing/hot-deals': typeof AppMarketingHotDealsRoute
  '/marketing/trending': typeof AppMarketingTrendingRoute
  '/orders/all': typeof AppOrdersAllRoute
  '/orders/invoices': typeof AppOrdersInvoicesRoute
  '/orders/returns': typeof AppOrdersReturnsRoute
  '/orders/shipping-methods': typeof AppOrdersShippingMethodsRoute
  '/orders/tracker': typeof AppOrdersTrackerRoute
  '/products/all': typeof AppProductsAllRoute
  '/products/atl-kits': typeof AppProductsAtlKitsRoute
  '/products/best-selling': typeof AppProductsBestSellingRoute
  '/products/brands': typeof AppProductsBrandsRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/dashboard': typeof AppProductsDashboardRoute
  '/products/new-arrival': typeof AppProductsNewArrivalRoute
  '/products/subcategories': typeof AppProductsSubcategoriesRoute
  '/products/variants': typeof AppProductsVariantsRoute
  '/projects/all': typeof AppProjectsAllRoute
  '/projects/dashboard': typeof AppProjectsDashboardRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/contact': typeof AppSettingsContactRoute
  '/settings/legal': typeof AppSettingsLegalRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/settings/seo': typeof AppSettingsSeoRoute
  '/settings/social': typeof AppSettingsSocialRoute
  '/users/all': typeof AppUsersAllRoute
  '/users/membership': typeof AppUsersMembershipRoute
  '/users/roles': typeof AppUsersRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/support': typeof AppSupportRoute
  '/affiliate/all': typeof AppAffiliateAllRoute
  '/affiliate/commission-tiers': typeof AppAffiliateCommissionTiersRoute
  '/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/affiliate/kyc': typeof AppAffiliateKycRoute
  '/affiliate/payouts': typeof AppAffiliatePayoutsRoute
  '/affiliate/referral-tracking': typeof AppAffiliateReferralTrackingRoute
  '/b2b/careers': typeof AppB2bCareersRoute
  '/b2b/inquiries': typeof AppB2bInquiriesRoute
  '/b2b/job-applications': typeof AppB2bJobApplicationsRoute
  '/b2b/video-gallery': typeof AppB2bVideoGalleryRoute
  '/content/blog': typeof AppContentBlogRoute
  '/content/faq': typeof AppContentFaqRoute
  '/content/tutorials': typeof AppContentTutorialsRoute
  '/content/video-gallery': typeof AppContentVideoGalleryRoute
  '/marketing/banners': typeof AppMarketingBannersRoute
  '/marketing/combo-offers': typeof AppMarketingComboOffersRoute
  '/marketing/flash-sales': typeof AppMarketingFlashSalesRoute
  '/marketing/hot-deals': typeof AppMarketingHotDealsRoute
  '/marketing/trending': typeof AppMarketingTrendingRoute
  '/orders/all': typeof AppOrdersAllRoute
  '/orders/invoices': typeof AppOrdersInvoicesRoute
  '/orders/returns': typeof AppOrdersReturnsRoute
  '/orders/shipping-methods': typeof AppOrdersShippingMethodsRoute
  '/orders/tracker': typeof AppOrdersTrackerRoute
  '/products/all': typeof AppProductsAllRoute
  '/products/atl-kits': typeof AppProductsAtlKitsRoute
  '/products/best-selling': typeof AppProductsBestSellingRoute
  '/products/brands': typeof AppProductsBrandsRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/dashboard': typeof AppProductsDashboardRoute
  '/products/new-arrival': typeof AppProductsNewArrivalRoute
  '/products/subcategories': typeof AppProductsSubcategoriesRoute
  '/products/variants': typeof AppProductsVariantsRoute
  '/projects/all': typeof AppProjectsAllRoute
  '/projects/dashboard': typeof AppProjectsDashboardRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/contact': typeof AppSettingsContactRoute
  '/settings/legal': typeof AppSettingsLegalRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/settings/seo': typeof AppSettingsSeoRoute
  '/settings/social': typeof AppSettingsSocialRoute
  '/users/all': typeof AppUsersAllRoute
  '/users/membership': typeof AppUsersMembershipRoute
  '/users/roles': typeof AppUsersRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/affiliate/all': typeof AppAffiliateAllRoute
  '/_app/affiliate/commission-tiers': typeof AppAffiliateCommissionTiersRoute
  '/_app/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/_app/affiliate/kyc': typeof AppAffiliateKycRoute
  '/_app/affiliate/payouts': typeof AppAffiliatePayoutsRoute
  '/_app/affiliate/referral-tracking': typeof AppAffiliateReferralTrackingRoute
  '/_app/b2b/careers': typeof AppB2bCareersRoute
  '/_app/b2b/inquiries': typeof AppB2bInquiriesRoute
  '/_app/b2b/job-applications': typeof AppB2bJobApplicationsRoute
  '/_app/b2b/video-gallery': typeof AppB2bVideoGalleryRoute
  '/_app/content/blog': typeof AppContentBlogRoute
  '/_app/content/faq': typeof AppContentFaqRoute
  '/_app/content/tutorials': typeof AppContentTutorialsRoute
  '/_app/content/video-gallery': typeof AppContentVideoGalleryRoute
  '/_app/marketing/banners': typeof AppMarketingBannersRoute
  '/_app/marketing/combo-offers': typeof AppMarketingComboOffersRoute
  '/_app/marketing/flash-sales': typeof AppMarketingFlashSalesRoute
  '/_app/marketing/hot-deals': typeof AppMarketingHotDealsRoute
  '/_app/marketing/trending': typeof AppMarketingTrendingRoute
  '/_app/orders/all': typeof AppOrdersAllRoute
  '/_app/orders/invoices': typeof AppOrdersInvoicesRoute
  '/_app/orders/returns': typeof AppOrdersReturnsRoute
  '/_app/orders/shipping-methods': typeof AppOrdersShippingMethodsRoute
  '/_app/orders/tracker': typeof AppOrdersTrackerRoute
  '/_app/products/all': typeof AppProductsAllRoute
  '/_app/products/atl-kits': typeof AppProductsAtlKitsRoute
  '/_app/products/best-selling': typeof AppProductsBestSellingRoute
  '/_app/products/brands': typeof AppProductsBrandsRoute
  '/_app/products/categories': typeof AppProductsCategoriesRoute
  '/_app/products/dashboard': typeof AppProductsDashboardRoute
  '/_app/products/new-arrival': typeof AppProductsNewArrivalRoute
  '/_app/products/subcategories': typeof AppProductsSubcategoriesRoute
  '/_app/products/variants': typeof AppProductsVariantsRoute
  '/_app/projects/all': typeof AppProjectsAllRoute
  '/_app/projects/dashboard': typeof AppProjectsDashboardRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/contact': typeof AppSettingsContactRoute
  '/_app/settings/legal': typeof AppSettingsLegalRoute
  '/_app/settings/payments': typeof AppSettingsPaymentsRoute
  '/_app/settings/seo': typeof AppSettingsSeoRoute
  '/_app/settings/social': typeof AppSettingsSocialRoute
  '/_app/users/all': typeof AppUsersAllRoute
  '/_app/users/membership': typeof AppUsersMembershipRoute
  '/_app/users/roles': typeof AppUsersRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/affiliate/all'
    | '/affiliate/commission-tiers'
    | '/affiliate/dashboard'
    | '/affiliate/kyc'
    | '/affiliate/payouts'
    | '/affiliate/referral-tracking'
    | '/b2b/careers'
    | '/b2b/inquiries'
    | '/b2b/job-applications'
    | '/b2b/video-gallery'
    | '/content/blog'
    | '/content/faq'
    | '/content/tutorials'
    | '/content/video-gallery'
    | '/marketing/banners'
    | '/marketing/combo-offers'
    | '/marketing/flash-sales'
    | '/marketing/hot-deals'
    | '/marketing/trending'
    | '/orders/all'
    | '/orders/invoices'
    | '/orders/returns'
    | '/orders/shipping-methods'
    | '/orders/tracker'
    | '/products/all'
    | '/products/atl-kits'
    | '/products/best-selling'
    | '/products/brands'
    | '/products/categories'
    | '/products/dashboard'
    | '/products/new-arrival'
    | '/products/subcategories'
    | '/products/variants'
    | '/projects/all'
    | '/projects/dashboard'
    | '/settings/company'
    | '/settings/contact'
    | '/settings/legal'
    | '/settings/payments'
    | '/settings/seo'
    | '/settings/social'
    | '/users/all'
    | '/users/membership'
    | '/users/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/affiliate/all'
    | '/affiliate/commission-tiers'
    | '/affiliate/dashboard'
    | '/affiliate/kyc'
    | '/affiliate/payouts'
    | '/affiliate/referral-tracking'
    | '/b2b/careers'
    | '/b2b/inquiries'
    | '/b2b/job-applications'
    | '/b2b/video-gallery'
    | '/content/blog'
    | '/content/faq'
    | '/content/tutorials'
    | '/content/video-gallery'
    | '/marketing/banners'
    | '/marketing/combo-offers'
    | '/marketing/flash-sales'
    | '/marketing/hot-deals'
    | '/marketing/trending'
    | '/orders/all'
    | '/orders/invoices'
    | '/orders/returns'
    | '/orders/shipping-methods'
    | '/orders/tracker'
    | '/products/all'
    | '/products/atl-kits'
    | '/products/best-selling'
    | '/products/brands'
    | '/products/categories'
    | '/products/dashboard'
    | '/products/new-arrival'
    | '/products/subcategories'
    | '/products/variants'
    | '/projects/all'
    | '/projects/dashboard'
    | '/settings/company'
    | '/settings/contact'
    | '/settings/legal'
    | '/settings/payments'
    | '/settings/seo'
    | '/settings/social'
    | '/users/all'
    | '/users/membership'
    | '/users/roles'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/support'
    | '/_app/affiliate/all'
    | '/_app/affiliate/commission-tiers'
    | '/_app/affiliate/dashboard'
    | '/_app/affiliate/kyc'
    | '/_app/affiliate/payouts'
    | '/_app/affiliate/referral-tracking'
    | '/_app/b2b/careers'
    | '/_app/b2b/inquiries'
    | '/_app/b2b/job-applications'
    | '/_app/b2b/video-gallery'
    | '/_app/content/blog'
    | '/_app/content/faq'
    | '/_app/content/tutorials'
    | '/_app/content/video-gallery'
    | '/_app/marketing/banners'
    | '/_app/marketing/combo-offers'
    | '/_app/marketing/flash-sales'
    | '/_app/marketing/hot-deals'
    | '/_app/marketing/trending'
    | '/_app/orders/all'
    | '/_app/orders/invoices'
    | '/_app/orders/returns'
    | '/_app/orders/shipping-methods'
    | '/_app/orders/tracker'
    | '/_app/products/all'
    | '/_app/products/atl-kits'
    | '/_app/products/best-selling'
    | '/_app/products/brands'
    | '/_app/products/categories'
    | '/_app/products/dashboard'
    | '/_app/products/new-arrival'
    | '/_app/products/subcategories'
    | '/_app/products/variants'
    | '/_app/projects/all'
    | '/_app/projects/dashboard'
    | '/_app/settings/company'
    | '/_app/settings/contact'
    | '/_app/settings/legal'
    | '/_app/settings/payments'
    | '/_app/settings/seo'
    | '/_app/settings/social'
    | '/_app/users/all'
    | '/_app/users/membership'
    | '/_app/users/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/roles': {
      id: '/_app/users/roles'
      path: '/users/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof AppUsersRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/membership': {
      id: '/_app/users/membership'
      path: '/users/membership'
      fullPath: '/users/membership'
      preLoaderRoute: typeof AppUsersMembershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/all': {
      id: '/_app/users/all'
      path: '/users/all'
      fullPath: '/users/all'
      preLoaderRoute: typeof AppUsersAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/social': {
      id: '/_app/settings/social'
      path: '/settings/social'
      fullPath: '/settings/social'
      preLoaderRoute: typeof AppSettingsSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/seo': {
      id: '/_app/settings/seo'
      path: '/settings/seo'
      fullPath: '/settings/seo'
      preLoaderRoute: typeof AppSettingsSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/payments': {
      id: '/_app/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AppSettingsPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/legal': {
      id: '/_app/settings/legal'
      path: '/settings/legal'
      fullPath: '/settings/legal'
      preLoaderRoute: typeof AppSettingsLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/contact': {
      id: '/_app/settings/contact'
      path: '/settings/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof AppSettingsContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/dashboard': {
      id: '/_app/projects/dashboard'
      path: '/projects/dashboard'
      fullPath: '/projects/dashboard'
      preLoaderRoute: typeof AppProjectsDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/all': {
      id: '/_app/projects/all'
      path: '/projects/all'
      fullPath: '/projects/all'
      preLoaderRoute: typeof AppProjectsAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/variants': {
      id: '/_app/products/variants'
      path: '/products/variants'
      fullPath: '/products/variants'
      preLoaderRoute: typeof AppProductsVariantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/subcategories': {
      id: '/_app/products/subcategories'
      path: '/products/subcategories'
      fullPath: '/products/subcategories'
      preLoaderRoute: typeof AppProductsSubcategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new-arrival': {
      id: '/_app/products/new-arrival'
      path: '/products/new-arrival'
      fullPath: '/products/new-arrival'
      preLoaderRoute: typeof AppProductsNewArrivalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/dashboard': {
      id: '/_app/products/dashboard'
      path: '/products/dashboard'
      fullPath: '/products/dashboard'
      preLoaderRoute: typeof AppProductsDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/categories': {
      id: '/_app/products/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof AppProductsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/brands': {
      id: '/_app/products/brands'
      path: '/products/brands'
      fullPath: '/products/brands'
      preLoaderRoute: typeof AppProductsBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/best-selling': {
      id: '/_app/products/best-selling'
      path: '/products/best-selling'
      fullPath: '/products/best-selling'
      preLoaderRoute: typeof AppProductsBestSellingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/atl-kits': {
      id: '/_app/products/atl-kits'
      path: '/products/atl-kits'
      fullPath: '/products/atl-kits'
      preLoaderRoute: typeof AppProductsAtlKitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/all': {
      id: '/_app/products/all'
      path: '/products/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof AppProductsAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/tracker': {
      id: '/_app/orders/tracker'
      path: '/orders/tracker'
      fullPath: '/orders/tracker'
      preLoaderRoute: typeof AppOrdersTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/shipping-methods': {
      id: '/_app/orders/shipping-methods'
      path: '/orders/shipping-methods'
      fullPath: '/orders/shipping-methods'
      preLoaderRoute: typeof AppOrdersShippingMethodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/returns': {
      id: '/_app/orders/returns'
      path: '/orders/returns'
      fullPath: '/orders/returns'
      preLoaderRoute: typeof AppOrdersReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/invoices': {
      id: '/_app/orders/invoices'
      path: '/orders/invoices'
      fullPath: '/orders/invoices'
      preLoaderRoute: typeof AppOrdersInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/all': {
      id: '/_app/orders/all'
      path: '/orders/all'
      fullPath: '/orders/all'
      preLoaderRoute: typeof AppOrdersAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/trending': {
      id: '/_app/marketing/trending'
      path: '/marketing/trending'
      fullPath: '/marketing/trending'
      preLoaderRoute: typeof AppMarketingTrendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/hot-deals': {
      id: '/_app/marketing/hot-deals'
      path: '/marketing/hot-deals'
      fullPath: '/marketing/hot-deals'
      preLoaderRoute: typeof AppMarketingHotDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/flash-sales': {
      id: '/_app/marketing/flash-sales'
      path: '/marketing/flash-sales'
      fullPath: '/marketing/flash-sales'
      preLoaderRoute: typeof AppMarketingFlashSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/combo-offers': {
      id: '/_app/marketing/combo-offers'
      path: '/marketing/combo-offers'
      fullPath: '/marketing/combo-offers'
      preLoaderRoute: typeof AppMarketingComboOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/banners': {
      id: '/_app/marketing/banners'
      path: '/marketing/banners'
      fullPath: '/marketing/banners'
      preLoaderRoute: typeof AppMarketingBannersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/video-gallery': {
      id: '/_app/content/video-gallery'
      path: '/content/video-gallery'
      fullPath: '/content/video-gallery'
      preLoaderRoute: typeof AppContentVideoGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/tutorials': {
      id: '/_app/content/tutorials'
      path: '/content/tutorials'
      fullPath: '/content/tutorials'
      preLoaderRoute: typeof AppContentTutorialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/faq': {
      id: '/_app/content/faq'
      path: '/content/faq'
      fullPath: '/content/faq'
      preLoaderRoute: typeof AppContentFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/blog': {
      id: '/_app/content/blog'
      path: '/content/blog'
      fullPath: '/content/blog'
      preLoaderRoute: typeof AppContentBlogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/b2b/video-gallery': {
      id: '/_app/b2b/video-gallery'
      path: '/b2b/video-gallery'
      fullPath: '/b2b/video-gallery'
      preLoaderRoute: typeof AppB2bVideoGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/b2b/job-applications': {
      id: '/_app/b2b/job-applications'
      path: '/b2b/job-applications'
      fullPath: '/b2b/job-applications'
      preLoaderRoute: typeof AppB2bJobApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/b2b/inquiries': {
      id: '/_app/b2b/inquiries'
      path: '/b2b/inquiries'
      fullPath: '/b2b/inquiries'
      preLoaderRoute: typeof AppB2bInquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/b2b/careers': {
      id: '/_app/b2b/careers'
      path: '/b2b/careers'
      fullPath: '/b2b/careers'
      preLoaderRoute: typeof AppB2bCareersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/referral-tracking': {
      id: '/_app/affiliate/referral-tracking'
      path: '/affiliate/referral-tracking'
      fullPath: '/affiliate/referral-tracking'
      preLoaderRoute: typeof AppAffiliateReferralTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/payouts': {
      id: '/_app/affiliate/payouts'
      path: '/affiliate/payouts'
      fullPath: '/affiliate/payouts'
      preLoaderRoute: typeof AppAffiliatePayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/kyc': {
      id: '/_app/affiliate/kyc'
      path: '/affiliate/kyc'
      fullPath: '/affiliate/kyc'
      preLoaderRoute: typeof AppAffiliateKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/dashboard': {
      id: '/_app/affiliate/dashboard'
      path: '/affiliate/dashboard'
      fullPath: '/affiliate/dashboard'
      preLoaderRoute: typeof AppAffiliateDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/commission-tiers': {
      id: '/_app/affiliate/commission-tiers'
      path: '/affiliate/commission-tiers'
      fullPath: '/affiliate/commission-tiers'
      preLoaderRoute: typeof AppAffiliateCommissionTiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/all': {
      id: '/_app/affiliate/all'
      path: '/affiliate/all'
      fullPath: '/affiliate/all'
      preLoaderRoute: typeof AppAffiliateAllRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSupportRoute: typeof AppSupportRoute
  AppAffiliateAllRoute: typeof AppAffiliateAllRoute
  AppAffiliateCommissionTiersRoute: typeof AppAffiliateCommissionTiersRoute
  AppAffiliateDashboardRoute: typeof AppAffiliateDashboardRoute
  AppAffiliateKycRoute: typeof AppAffiliateKycRoute
  AppAffiliatePayoutsRoute: typeof AppAffiliatePayoutsRoute
  AppAffiliateReferralTrackingRoute: typeof AppAffiliateReferralTrackingRoute
  AppB2bCareersRoute: typeof AppB2bCareersRoute
  AppB2bInquiriesRoute: typeof AppB2bInquiriesRoute
  AppB2bJobApplicationsRoute: typeof AppB2bJobApplicationsRoute
  AppB2bVideoGalleryRoute: typeof AppB2bVideoGalleryRoute
  AppContentBlogRoute: typeof AppContentBlogRoute
  AppContentFaqRoute: typeof AppContentFaqRoute
  AppContentTutorialsRoute: typeof AppContentTutorialsRoute
  AppContentVideoGalleryRoute: typeof AppContentVideoGalleryRoute
  AppMarketingBannersRoute: typeof AppMarketingBannersRoute
  AppMarketingComboOffersRoute: typeof AppMarketingComboOffersRoute
  AppMarketingFlashSalesRoute: typeof AppMarketingFlashSalesRoute
  AppMarketingHotDealsRoute: typeof AppMarketingHotDealsRoute
  AppMarketingTrendingRoute: typeof AppMarketingTrendingRoute
  AppOrdersAllRoute: typeof AppOrdersAllRoute
  AppOrdersInvoicesRoute: typeof AppOrdersInvoicesRoute
  AppOrdersReturnsRoute: typeof AppOrdersReturnsRoute
  AppOrdersShippingMethodsRoute: typeof AppOrdersShippingMethodsRoute
  AppOrdersTrackerRoute: typeof AppOrdersTrackerRoute
  AppProductsAllRoute: typeof AppProductsAllRoute
  AppProductsAtlKitsRoute: typeof AppProductsAtlKitsRoute
  AppProductsBestSellingRoute: typeof AppProductsBestSellingRoute
  AppProductsBrandsRoute: typeof AppProductsBrandsRoute
  AppProductsCategoriesRoute: typeof AppProductsCategoriesRoute
  AppProductsDashboardRoute: typeof AppProductsDashboardRoute
  AppProductsNewArrivalRoute: typeof AppProductsNewArrivalRoute
  AppProductsSubcategoriesRoute: typeof AppProductsSubcategoriesRoute
  AppProductsVariantsRoute: typeof AppProductsVariantsRoute
  AppProjectsAllRoute: typeof AppProjectsAllRoute
  AppProjectsDashboardRoute: typeof AppProjectsDashboardRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsContactRoute: typeof AppSettingsContactRoute
  AppSettingsLegalRoute: typeof AppSettingsLegalRoute
  AppSettingsPaymentsRoute: typeof AppSettingsPaymentsRoute
  AppSettingsSeoRoute: typeof AppSettingsSeoRoute
  AppSettingsSocialRoute: typeof AppSettingsSocialRoute
  AppUsersAllRoute: typeof AppUsersAllRoute
  AppUsersMembershipRoute: typeof AppUsersMembershipRoute
  AppUsersRolesRoute: typeof AppUsersRolesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSupportRoute: AppSupportRoute,
  AppAffiliateAllRoute: AppAffiliateAllRoute,
  AppAffiliateCommissionTiersRoute: AppAffiliateCommissionTiersRoute,
  AppAffiliateDashboardRoute: AppAffiliateDashboardRoute,
  AppAffiliateKycRoute: AppAffiliateKycRoute,
  AppAffiliatePayoutsRoute: AppAffiliatePayoutsRoute,
  AppAffiliateReferralTrackingRoute: AppAffiliateReferralTrackingRoute,
  AppB2bCareersRoute: AppB2bCareersRoute,
  AppB2bInquiriesRoute: AppB2bInquiriesRoute,
  AppB2bJobApplicationsRoute: AppB2bJobApplicationsRoute,
  AppB2bVideoGalleryRoute: AppB2bVideoGalleryRoute,
  AppContentBlogRoute: AppContentBlogRoute,
  AppContentFaqRoute: AppContentFaqRoute,
  AppContentTutorialsRoute: AppContentTutorialsRoute,
  AppContentVideoGalleryRoute: AppContentVideoGalleryRoute,
  AppMarketingBannersRoute: AppMarketingBannersRoute,
  AppMarketingComboOffersRoute: AppMarketingComboOffersRoute,
  AppMarketingFlashSalesRoute: AppMarketingFlashSalesRoute,
  AppMarketingHotDealsRoute: AppMarketingHotDealsRoute,
  AppMarketingTrendingRoute: AppMarketingTrendingRoute,
  AppOrdersAllRoute: AppOrdersAllRoute,
  AppOrdersInvoicesRoute: AppOrdersInvoicesRoute,
  AppOrdersReturnsRoute: AppOrdersReturnsRoute,
  AppOrdersShippingMethodsRoute: AppOrdersShippingMethodsRoute,
  AppOrdersTrackerRoute: AppOrdersTrackerRoute,
  AppProductsAllRoute: AppProductsAllRoute,
  AppProductsAtlKitsRoute: AppProductsAtlKitsRoute,
  AppProductsBestSellingRoute: AppProductsBestSellingRoute,
  AppProductsBrandsRoute: AppProductsBrandsRoute,
  AppProductsCategoriesRoute: AppProductsCategoriesRoute,
  AppProductsDashboardRoute: AppProductsDashboardRoute,
  AppProductsNewArrivalRoute: AppProductsNewArrivalRoute,
  AppProductsSubcategoriesRoute: AppProductsSubcategoriesRoute,
  AppProductsVariantsRoute: AppProductsVariantsRoute,
  AppProjectsAllRoute: AppProjectsAllRoute,
  AppProjectsDashboardRoute: AppProjectsDashboardRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsContactRoute: AppSettingsContactRoute,
  AppSettingsLegalRoute: AppSettingsLegalRoute,
  AppSettingsPaymentsRoute: AppSettingsPaymentsRoute,
  AppSettingsSeoRoute: AppSettingsSeoRoute,
  AppSettingsSocialRoute: AppSettingsSocialRoute,
  AppUsersAllRoute: AppUsersAllRoute,
  AppUsersMembershipRoute: AppUsersMembershipRoute,
  AppUsersRolesRoute: AppUsersRolesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
