import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MobileNavbar from "@/components/MobileNavbar";
import { Toaster } from 'react-hot-toast';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DSM-Electro",
  description: "Generated by create next app",
};

import GlobalBottomSections from "@/components/shared/GlobalBottomSections";
import { Providers } from "@/redux/providers";
import AffiliateTracker from "@/components/AffiliateTracker";
import GlobalLoader from "@/components/shared/GlobalLoader";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <GlobalLoader />
          <Toaster position="bottom-center" reverseOrder={false} />
          <AffiliateTracker />
          <div className="relative z-[999999]">
            <Navbar />
          </div>
          {children}
          <div className="relative z-[999999]">
            <GlobalBottomSections />
            <Footer />
            <MobileNavbar />
          </div>
        </Providers>
      </body>
    </html>
  );
}
