import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MobileNavbar from "@/components/MobileNavbar";
import { Toaster } from 'react-hot-toast';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DSM-Electro",
  description: "Generated by create next app",
};

import GlobalBottomSections from "@/components/shared/GlobalBottomSections";
import { Providers } from "@/redux/providers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Toaster position="bottom-center" reverseOrder={false} />
          <Navbar />
          {children}
          <GlobalBottomSections />
          <Footer />
          <MobileNavbar />
        </Providers>
      </body>
    </html>
  );
}
